.\" internsctl.
.\" custom linux command.
.TH internsctl 1 "1.0" "internsctl"
.SH NAME
internsctl \- custom linux command 

.SH SYNOPSIS
.B internsctl
.RB [OPTION]...
.RB [INFO]...

.SH DESCRIPTION
internsctl for custom linux command. These commands are like getting system info , create new users and file info.

.SH OPTIONS
.TP
.B cpu getinfo
cpu information of my server
.TP
.B memory getinfo
memory information of my server
.TP
.B user create <username>
create a new user on my server
.TP
.B user list
list all the users
.TP
.B User list --sudo-only
list all the users with sudo permissions
.TP
.B file getinfo <file-name>	
information about the file
.TP
.B file getinfo <file-name>
information about the file
 


.SH AUTHOR
Harpreet Kaur
